/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dht */

#ifndef _Included_Dht
#define _Included_Dht
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dht
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Dht_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
