//  How to access GPIO registers from C-code on the Raspberry-Pi
//  Example program
//  15-January-2012
//  Dom and Gert
//
//gcc DHT.c -o DHT -lwiringPi -std=gnu99 -lbcm2835	
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <dirent.h>
#include <fcntl.h>
#include <assert.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <unistd.h>
#include "Dht.h" //this header file was generated by javah
#include <wiringPi.h>

#define MAXTIMINGS 100
#define DHTPIN 0



int32_t bits[250], data[100];
int32_t bitidx = 0;

JNIEXPORT jlong JNICALL Java_Dht_readDHT(JNIEnv *env, jobject obj)

{
  int32_t counter = 0;
  int32_t j	= 0;
  int32_t laststate = HIGH;
  uint64_t humadity_temperature;

  wiringPiSetup();
  
  // Set GPIO pin to output
  pinMode(DHTPIN, OUTPUT);
  
  //set to HIGH
  digitalWrite(DHTPIN, HIGH);
  usleep(500000);  // 500 ms
  
  //set to LOW
  digitalWrite(DHTPIN, LOW);
  usleep(20000);
  
 //set to input
  pinMode(DHTPIN, INPUT);
  pullUpDnControl(DHTPIN, PUD_UP);
  data[0] = data[1] = data[2] = data[3] = data[4] = 0;

  // wait for pin to drop?
  //wait until level is HIGH
  while(digitalRead(DHTPIN) == HIGH)
  {
    usleep(10);
  }

  // read data!
  for (int32_t i = 0; i < MAXTIMINGS; i++) 
  {
    counter = 0;
    
    //wait until level is HIGH
    while(digitalRead(DHTPIN) == laststate) 
    {
	counter++;
	//nanosleep(1);		// overclocking might change this?
        if (counter == 1000)
	  break;
    }

   laststate = digitalRead(DHTPIN);
    
    if (counter == 1000) break;
    bits[bitidx++] = counter;

    if ((i>3) && (i%2 == 0)) {
      // shove each bit into the storage bytes
      data[j/8] <<= 1;
      if (counter > 200)
        data[j/8] |= 1;
      j++;
    }
  }
	
     // yay!
	humadity_temperature = (uint16_t)(data[0] << 16 )| (uint16_t) data[2];

  	return humadity_temperature;
}

 
