/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Us */

#ifndef _Included_Us
#define _Included_Us
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Us
 * Method:    distance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Us_distance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
