/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HumadityTemperature */

#ifndef _Included_HumadityTemperature
#define _Included_HumadityTemperature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HumadityTemperature
 * Method:    readDHT
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_HumadityTemperature_readDHT
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
